Create assignment2
alexandracalota/CodeU pull request #2
Opened 2017-05-28 19:36 UTC by alexandracalota

2017-06-07 20:54 UTC, kkasiacodeu requested changes
Nice work! :) Good algorithms, only a few minor comments to address.

2017-06-07 20:54 UTC, kkasiacodeu commented on assignment2
> +	public void insertNode(int key, int parentKey, String position) {
if you only allow "L" and "R" values here you can use char instead of String.

2017-06-07 20:54 UTC, kkasiacodeu commented on assignment2
> +	public static Boolean auxQ1(Stack<Node> parents, int key, Node root) {
what does the name if this method stand for? Could you rename it so that it says what it does?

2017-06-07 20:54 UTC, kkasiacodeu commented on assignment2
> +	public static Boolean auxQ1(Stack<Node> parents, int key, Node root) {
You don't have to wrap the primitive boolean into a Boolean object in the return type.

2017-06-08 05:53 UTC, alexandracalota commented on assignment2
> +	public static Boolean auxQ1(Stack<Node> parents, int key, Node root) {
I changed the name so it is suggestive.

2017-06-08 05:54 UTC, alexandracalota commented on assignment2
> +	public static Boolean auxQ1(Stack<Node> parents, int key, Node root) {
I changed the return type to boolean.

2017-06-08 05:54 UTC, alexandracalota commented on assignment2
> +	public void insertNode(int key, int parentKey, String position) {
Yes, that would be simpler. I change the type of the argument.

2017-06-10 20:44 UTC, merged