Assignment3
alexandracalota/CodeU pull request #5
Opened 2017-06-23 11:49 UTC by alexandracalota

2017-06-26 15:43 UTC, kkasiacodeu requested changes
The algorithm is good, well done! :)

Just some improvements to the code quality and some data structures used.

But generally great job 👍

2017-06-26 15:43 UTC, kkasiacodeu commented on Dictionary.java
> +	public void setPrefixes(LinkedList<String> prefixes) {
You don't want this to be settable at all. This should not be mutable from outside of this class at all.

2017-06-26 15:43 UTC, kkasiacodeu commented on Dictionary.java
> +	public void setWords(LinkedList<String> words) {
You don't want this to be settable externally. If this is set some time after the creation of the class instance, the prefixes will not be computed for it.

2017-06-26 15:43 UTC, kkasiacodeu commented on Dictionary.java
> +		this.prefixes = new LinkedList<String>();
I would suggest extracting the computing part outside of the constructor. It is generally bad practice to have any work done in the constructor. I suggest you arrange it in the following way: the constructor only initializes the required fields, then we provide a method that sets "words" list and computes "prefixes" list.

2017-06-26 15:43 UTC, kkasiacodeu commented on SearchWord.java
> +	public int[][] visited;
this can be a matrix of booleans instead of ints.

2017-06-26 15:43 UTC, kkasiacodeu commented on SearchWord.java
> +			LinkedList<String> validWords, String word) {
Why is validWords a LinkedList? You perform two operations on it: contains(word) and add(word). There are better data structures to handle these. What is the complexity for those operations for the linked list?

2017-06-26 15:43 UTC, kkasiacodeu commented on Dictionary.java
> +	private LinkedList<String> words;
Could this be a different data structure than LinkedList (better for the complexity of performed operations)?

2017-06-26 15:43 UTC, kkasiacodeu commented on Dictionary.java
> +	private LinkedList<String> prefixes;
Could this be a different data structure than LinkedList (better for the complexity of performed operations)?

2017-06-26 15:43 UTC, kkasiacodeu commented on SearchWord.java
> +	public void applyBFS(int rows, int columns, int posX, int posY, char[][] characters, Dictionary dict,
This is an implementation of DFS not BFS :)

2017-06-28 21:37 UTC, alexandracalota commented on Dictionary.java
> +	private LinkedList<String> words;
Yes, HashSet is faster thank LinkedList. I have changed the data structures to that.

2017-06-28 21:38 UTC, alexandracalota commented on Dictionary.java
> +		this.prefixes = new LinkedList<String>();
I see, thank you for your advice. I've changed the constructor, please let me know if it's alright now.

2017-06-28 21:41 UTC, alexandracalota commented on SearchWord.java
> +			LinkedList<String> validWords, String word) {
I would say contains(word) has O(n) complexity and that of add(word) O(1). A HashSet is better, as both contains and add have O(1) complexity.

2017-08-12 14:32 UTC, merged